// export const RootUrl = "http://192.168.0.104:3005";

export const authTypes = {
  LOCAL_LOGIN: "LOCAL_LOGIN",
  LOCAL_LOGIN_SUCCESS: "LOCAL_LOGIN_SUCCESS",
  LOCAL_LOGIN_FAIL: "LOCAL_LOGIN_FAIL",

  SET_LOCAL_LOGIN: "SET_LOCAL_LOGIN",

  LOGIN_USER: "LOGIN_USER",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAIL: "LOGIN_USER_FAIL",

  GET_USER_DETAILS: "GET_USER_DETAILS",
  GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
  GET_USER_DETAILS_FAIL: "GET_USER_DETAILS_FAIL",

  LOGOUT_USER: "LOGOUT_USER",
};

export const commonTypes = {
  GET_COURSES: "GET_COURSES",
  GET_COURSES_SUCCESS: "GET_COURSES_SUCCESS",
  GET_COURSES_FAIL: "GET_COURSES_FAIL",

  GET_ASSIGNMENTS: "GET_ASSIGNMENTS",
  GET_ASSIGNMENTS_SUCCESS: "GET_ASSIGNMENTS_SUCCESS",
  GET_ASSIGNMENTS_FAIL: "GET_ASSIGNMENTS_FAIL",

  SET_A_MESSAGE: "SET_A_MESSAGE",

  SET_MESSAGES: "SET_MESSAGES",

  CLEAN_MESSAGES: "CLEAN_MESSAGES",
};

export const userTypes = {
  CREATE_USER: "CREATE_USER",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: "CREATE_USER_FAIL",

  UPDATE_USER: "UPDATE_USER",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAIL: "UPDATE_USER_FAIL",

  GET_ALL_USERS: "GET_ALL_USERS",
  GET_ALL_USERS_SUCCESS: "GET_ALL_USERS_SUCCESS",
  GET_ALL_USERS_FAIL: "GET_ALL_USERS_FAIL",

  DELETE_USER: "DELETE_USER",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIL: "DELETE_USER_FAIL",
};

export const utilTypes = {
  TOGGLE_DRAWER: "TOGGLE_DRAWER",

  SET_MESSAGES: "SET_MESSAGES",

  TOGGLE_FULL_SCREEN: "TOGGLE_FULL_SCREEN",

  OPEN_MODAL: "OPEN_MODAL",

  CLOSE_MODAL: "CLOSE_MODAL",
};

export const organizationTypes = {
  CREATE_ORGANIZATION: "CREATE_ORGANIZATION",
  CREATE_ORGANIZATION_SUCCESS: "CREATE_ORGANIZATION_SUCCESS",
  CREATE_ORGANIZATION_FAIL: "CREATE_ORGANIZATION_FAIL",
};
