// export const RootUrl = "http://192.168.0.104:3005";

export const utilTypes = {
  TOGGLE_DRAWER: "TOGGLE_DRAWER",


  OPEN_MODAL: "OPEN_MODAL",

  CLOSE_MODAL: "CLOSE_MODAL",

  PRICING_SELECTION: 'PRICING_SELECTION',
  SUBJECT_SELECTION: 'SUBJECT_SELECTION',

  SUBMIT_CONTACT: "SUBMIT_CONTACT",
  SUBMIT_CONTACT_SUCCESS: "SUBMIT_CONTACT_SUCCESS",
  SUBMIT_CONTACT_FAIL: "SUBMIT_CONTACT_FAIL",

};

